### ISSUE TITLE
Cannot define custom border size

### ISSUE THREAD

**Issue by simonizljubljane** [batistein/tailwindcss-border-gradient-radius#4]
This does not work:
```
linearBorderGradients: {
    ...
    border: {
        '3': '3px',
    },
},
```

But if I change `border` to `borders`, then `gradient-border-3` works (I still have issues with: `border-3`)
```
linearBorderGradients: {
    ...
    borders: {
        '3': '3px',
    },
},
```

**Comment by batistein** [comment]
@simonizljubljane Your right there is a typo in the Readme. I fixed that. border-3 is as i know from tailwind itself. and 3 is not defined as a default. I fixed that in the Readme. The plugin is also updated for tailwind 3
